### ISSUE TITLE
No way to change recording output destination.

### ISSUE THREAD

**Issue by CaptainRick218** [marissa999/decky-recorder#6]
A big issue for people with a 64 GB model of the Steam Deck is minimal storage space after awhile. Even if you factory reset, and reinstall the bare essentials, it gets tedious after awhile.

I don't know the full capabilities of this plug in yet, or if it'll even be possible, but letting the user decide to output the recorded videos to a folder on their external drive or mounted micro SD card would be a godsend, cause even a 10 minute video could end up being over 2 GB in size depending on the quality.

**Comment by marissa999** [comment]
Oh funnily that is actually a feature I am kind of working on already :D I already added the code for setting the directory to the python backend, I still need to figure out how to have a comfy way for the user to pick a directory in the frontend, and most importantly how to save settings. Because I am sure nobody would want to re-setup the output folder every time

**Comment by cow-killer** [comment]
> I still need to figure out how to have a comfy way for the user to pick a directory in the frontend

Could just add a toggle "Save to MicroSD card" in Decky Recorder's menu, kind of like the mic toggle with 0.03.

**Comment by safijari** [comment]
Folder picker was added

**Comment by gagipetrovic** [comment]
Thanks for adding the folder picker. How do I access this?
