### ISSUE TITLE
The new Decky Loader 2.10.4 appears to have broken Decky Recorder

### ISSUE THREAD

**Issue by TheAntVenom** [marissa999/decky-recorder#65]
I had Decky Recorder working fine on Decky Loader 2.10.3, but upon updating to 2.10.4, it stopped working.

When I start the Deck now, the Instant Replay button stays locked to on. Turning it off and exiting / re-entering the menu shows it as still on, and any attempts to capture an Instant Replay causes the generic "Not enough time has passed to do a replay" error. I've tried multiple re-installations of Decky Loader and Decky Recorder, but I've not done a Decky Loader re-install that involved deleting the config.

Is anyone on 2.10.4 having the same issue? I've noticed that this project seems to be really slow going unfortunately, because it's one of the best plugins on the Deck, and I would hate to see this issue persist, like the Bluetooth headphones issue. This new issue really kills this plugin if I'm not the only one.

**Comment by donynx** [comment]
Just created this account to share my workaround.
 You will have to install a previous version of Decky Loader. The problem is, when you try to reinstall it, it automatically gives the latest version and pre-release version (which both broke Decky Recorder).

However, if you use the offline installer you can go back to whatever version you want.

I found [this](https://github.com/SteamDeckHomebrew/decky-loader/issues/492#issuecomment-1686747658) offline installer. Extract it wherever you want, just don't run it yet, the person who packed this file use the 'v2.10.4-pre7' and it will give you the same problem (I found the offline installer on Decky Loader's discord btw).

To get a previous file, go to 'Releases' in Decky Loader Github and look for 'v2.10.3' [here](https://github.com/SteamDeckHomebrew/decky-loader/releases/tag/v2.10.3), download the 'Plugin Loader' file and replace it with the file of the same name that you got when unzipping the Decky Loader installer.

Now follow the [instructions ](https://github.com/SteamDeckHomebrew/decky-loader/issues/492#issuecomment-1686747658), open your terminal (Konsole) and run this:

1. chmod +x install_release_offline.sh
2. ./install_release_offline.sh

And with that you're supposed to got a previous version of Decky Loader. 

A little disclaimer:

*I don't write/know to code, I'm simply a regular user who had your same problem and decided to share my workaround, this should work but if you got stuck or something else happen, I probably won't t be able to help*

**Comment by spudpiggy** [comment]
bump, downgrading deckyloader shouldn't be a requirement to use this plugin now

**Comment by Conan179** [comment]
@donynx Replacing the PluginLoader file does not work, the version Installing version v2.10.4-pre7 is always installed for me.

**Comment by Conan179** [comment]
I've changed the install_release_offline.sh on line 32 and 33. The installation then works and the error is gone, Deckyrecorder works!

**Comment by spudpiggy** [comment]
1. just "i've fixed it and it works now" is useless information without saying exactly what they were changed to, better yet just send the new file
2. you shouldn't post two comments within minutes of each other, instead you should edit the first one

**Comment by donynx** [comment]
@spudpiggy Agreed. Ideally we shouldn't have to downgrade Decky loader in order to this plugin  to work, but on the mean time, is the only way I find to be able to use it (As OP mentioned, this plugin doesn't seems to be updated frequently).

@Conan179 Again, I'm just a regular user, so I can't really help but I do remember when I installed it, it said it was version v2.10.4-pre7. But remember we change the version file, and the offline installer was originally for version v2.10.4-pre7, maybe that's why you got that msg?

Regardless, it *SHOULD*  be fine without the need of editing anything else. At least, that's what I did...

**Comment by gagipetrovic** [comment]
> I had Decky Recorder working fine on Decky Loader 2.10.3, but upon updating to 2.10.4, it stopped working.
> 
> When I start the Deck now, the Instant Replay button stays locked to on. Turning it off and exiting / re-entering the menu shows it as still on, and any attempts to capture an Instant Replay causes the generic "Not enough time has passed to do a replay" error. I've tried multiple re-installations of Decky Loader and Decky Recorder, but I've not done a Decky Loader re-install that involved deleting the config.
> 
> Is anyone on 2.10.4 having the same issue? I've noticed that this project seems to be really slow going unfortunately, because it's one of the best plugins on the Deck, and I would hate to see this issue persist, like the Bluetooth headphones issue. This new issue really kills this plugin if I'm not the only one.

I have the same issue unfortunately...

**Comment by MediaWithMiles** [comment]
Also having the same issue......

> I had Decky Recorder working fine on Decky Loader 2.10.3, but upon updating to 2.10.4, it stopped working.
> 
> When I start the Deck now, the Instant Replay button stays locked to on. Turning it off and exiting / re-entering the menu shows it as still on, and any attempts to capture an Instant Replay causes the generic "Not enough time has passed to do a replay" error. I've tried multiple re-installations of Decky Loader and Decky Recorder, but I've not done a Decky Loader re-install that involved deleting the config.
> 
> Is anyone on 2.10.4 having the same issue? I've noticed that this project seems to be really slow going unfortunately, because it's one of the best plugins on the Deck, and I would hate to see this issue persist, like the Bluetooth headphones issue. This new issue really kills this plugin if I'm not the only one.

**Comment by TheAntVenom** [comment]
Heyo. Wanted to leave a comment about how I got 2.10.3. PartyWumpus in the Deck Homebrew Discord server.

"Grabbing the PluginLoader file from https://github.com/SteamDeckHomebrew/decky-loader/releases/tag/v2.10.3 and putting it in ~/homebrew/services should work"

This works, but you need to right click on PluginLoader, goto Properties, goto the 2nd tab, and set it as executable. Then 2.10.3 will load up after a restart. This'll be the solution I go with until the next major SteamOS update.

**Comment by MediaWithMiles** [comment]
> Heyo. Wanted to leave a comment about how I got 2.10.3. PartyWumpus in the Deck Homebrew Discord server.
> 
> "Grabbing the PluginLoader file from https://github.com/SteamDeckHomebrew/decky-loader/releases/tag/v2.10.3 and putting it in ~/homebrew/services should work"
> 
> This works, but you need to right click on PluginLoader, goto Properties, goto the 2nd tab, and set it as executable. Then 2.10.3 will load up after a restart. This'll be the solution I go with until the next major SteamOS update.

Will try this, thank you!

**Comment by MediaWithMiles** [comment]
> Checking on this now. Best as I can tell the author has not been active for a long while and I'm the only other maintainer. I also have not interacted with the Decky community in a while and do not intend to join the discord ever again so getting this deployed might be problematic.
> 
> Bear with me here, I'll try to have a fix out to the best of my abilities.

Thank you so much! I was wondering why there hasn't been an update in a while

**Comment by safijari** [comment]
I actually started maintaining a fork which has a number of other changes as well but I have not gotten around to releasing it yet. Will do that now after this fix.

Looks like the breakage happened due to a python version change. I seem to have fixed it locally.

**Comment by MediaWithMiles** [comment]
> Checking on this now. Best as I can tell the author has not been active for a long while and I'm the only other maintainer. I also have not interacted with the Decky community in a while and do not intend to join the discord ever again so getting this deployed might be problematic.
> 
> Bear with me here, I'll try to have a fix out to the best of my abilities.

Much appreciated!!

**Comment by safijari** [comment]
Well the latest version of Decky is being massively unstable for me. After running for about 5 minutes a bunch of stuff even in Decky's settings stops working (can't install / uninstall plugins, half the plugins work and the other half don't). Anyone else seeing this?

**Comment by prodbyloti** [comment]
the fix doesnt work for me. downgraded and still not able to manually recod & replay mode stuck

**Comment by Conan179** [comment]
I can confirm that, the error still occurs.

**Comment by Conan179** [comment]
Even worse, the new version shows the same bug with the older version v2.10.3 of Deckyloader.

**Comment by safijari** [comment]
An updated build is now on the Testing store. You can change your store channel to Testing and try installing it.

**Comment by Conan179** [comment]
> An updated build is now on the Testing store.
My apologies, I just saw the post.
I can confirm that the bug has been fixed, THANK YOU for your work!

**Comment by MediaWithMiles** [comment]
> An updated build is now on the Testing store. You can change your store channel to Testing and try installing it.

It works! Thank you so much!

**Comment by gagipetrovic** [comment]
Thank you so much for updating and fixing Decky Recorder. It works like a charm now! I also appreciate the automatic file name creation, based on what (game) is being captured. Well done! <3
